name: amatir
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- Default dari Flutter ---
  cupertino_icons: ^1.0.8

  # --- Firebase ---
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6 # Downgrading to valid version
  flutter_dotenv: ^6.0.0

  # --- State Management ---
  provider: ^6.1.2

  # --- Hardware Features ---
  geolocator: ^12.0.0
  image_picker: ^1.1.0
  mobile_scanner: ^5.1.0

  # --- Utilities ---
  intl: ^0.19.0
  uuid: ^4.3.3
  timeline_tile: ^2.0.0
  flutter_local_notifications: ^20.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
