// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXh_0a8yoP4UBqNucplFHoasFQZeloB2g',
    appId: '1:1041916996900:web:7f4c62982e2f6c150517b1',
    messagingSenderId: '1041916996900',
    projectId: 'logitrackapp-6a4be',
    authDomain: 'logitrackapp-6a4be.firebaseapp.com',
    storageBucket: 'logitrackapp-6a4be.firebasestorage.app',
    measurementId: 'G-M9M3TPHQF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3A0my1YMFS1qyYaBpxn0oy_IEGgGjgA4',
    appId: '1:1041916996900:android:7d12affdd89740c10517b1',
    messagingSenderId: '1041916996900',
    projectId: 'logitrackapp-6a4be',
    storageBucket: 'logitrackapp-6a4be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpLdXemn8xhgqYTMfHarryCvuYiQi6fmQ',
    appId: '1:1041916996900:ios:41c0a4a050cd938f0517b1',
    messagingSenderId: '1041916996900',
    projectId: 'logitrackapp-6a4be',
    storageBucket: 'logitrackapp-6a4be.firebasestorage.app',
    iosBundleId: 'com.example.amatir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpLdXemn8xhgqYTMfHarryCvuYiQi6fmQ',
    appId: '1:1041916996900:ios:41c0a4a050cd938f0517b1',
    messagingSenderId: '1041916996900',
    projectId: 'logitrackapp-6a4be',
    storageBucket: 'logitrackapp-6a4be.firebasestorage.app',
    iosBundleId: 'com.example.amatir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXh_0a8yoP4UBqNucplFHoasFQZeloB2g',
    appId: '1:1041916996900:web:9a7a5351c30dfd3f0517b1',
    messagingSenderId: '1041916996900',
    projectId: 'logitrackapp-6a4be',
    authDomain: 'logitrackapp-6a4be.firebaseapp.com',
    storageBucket: 'logitrackapp-6a4be.firebasestorage.app',
    measurementId: 'G-EL1L5GXJY4',
  );
}
